-- ============================================================
-- Punto Fit — Esquema Supabase
-- Pega TODO este archivo en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- ── 1. Tipos ────────────────────────────────────────────────

CREATE TYPE public.rol_usuario AS ENUM ('cliente', 'admin');

CREATE TYPE public.estado_pedido AS ENUM ('pendiente', 'pagado', 'completado', 'cancelado');

CREATE TYPE public.estado_envio AS ENUM ('preparando', 'en_transito', 'entregado', 'cancelado');

-- ── 2. Tablas ───────────────────────────────────────────────

-- Perfil de usuario (vinculado a auth.users de Supabase Auth)
CREATE TABLE public.usuarios (
    id          UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email       TEXT NOT NULL UNIQUE,
    nombre      TEXT,
    rol         public.rol_usuario NOT NULL DEFAULT 'cliente',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.productos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       TEXT NOT NULL,
    categoria    TEXT NOT NULL,
    precio       NUMERIC(10, 2) NOT NULL CHECK (precio >= 0),
    inventario   INTEGER NOT NULL DEFAULT 0 CHECK (inventario >= 0),
    imagen_url   TEXT NOT NULL,
    descripcion  TEXT,
    marca        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pedidos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  UUID NOT NULL REFERENCES public.usuarios (id) ON DELETE RESTRICT,
    total       NUMERIC(10, 2) NOT NULL CHECK (total >= 0),
    estado      public.estado_pedido NOT NULL DEFAULT 'pendiente',
    fecha       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.envios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido     BIGINT NOT NULL UNIQUE REFERENCES public.pedidos (id) ON DELETE CASCADE,
    direccion     TEXT NOT NULL,
    estado_envio  public.estado_envio NOT NULL DEFAULT 'preparando',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX idx_productos_categoria ON public.productos (categoria);
CREATE INDEX idx_pedidos_usuario ON public.pedidos (id_usuario);
CREATE INDEX idx_pedidos_fecha ON public.pedidos (fecha DESC);

-- ── 3. Trigger: crear perfil al registrarse ───────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.usuarios (id, email, nombre, rol)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data ->> 'nombre', split_part(NEW.email, '@', 1)),
        'cliente'
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- ── 4. Helper: ¿es admin? ─────────────────────────────────────

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.usuarios
        WHERE id = auth.uid()
          AND rol = 'admin'
    );
$$;

-- ── 5. Row Level Security (RLS) ───────────────────────────────

ALTER TABLE public.usuarios   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.envios     ENABLE ROW LEVEL SECURITY;

-- ── USUARIOS ──

-- Cada usuario ve su propio perfil
CREATE POLICY "usuarios_select_own"
    ON public.usuarios FOR SELECT
    TO authenticated
    USING (id = auth.uid());

-- Admin ve todos los perfiles
CREATE POLICY "usuarios_select_admin"
    ON public.usuarios FOR SELECT
    TO authenticated
    USING (public.is_admin());

-- Usuario actualiza su nombre (no puede cambiar su rol)
CREATE POLICY "usuarios_update_own"
    ON public.usuarios FOR UPDATE
    TO authenticated
    USING (id = auth.uid())
    WITH CHECK (id = auth.uid() AND rol = (SELECT u.rol FROM public.usuarios u WHERE u.id = auth.uid()));

-- ── PRODUCTOS ──

-- Cualquiera (incluso sin login) puede ver el catálogo
CREATE POLICY "productos_select_public"
    ON public.productos FOR SELECT
    TO anon, authenticated
    USING (true);

-- Solo admin inserta productos
CREATE POLICY "productos_insert_admin"
    ON public.productos FOR INSERT
    TO authenticated
    WITH CHECK (public.is_admin());

-- Solo admin actualiza productos
CREATE POLICY "productos_update_admin"
    ON public.productos FOR UPDATE
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Solo admin elimina productos
CREATE POLICY "productos_delete_admin"
    ON public.productos FOR DELETE
    TO authenticated
    USING (public.is_admin());

-- ── PEDIDOS ──

-- Cliente ve solo sus pedidos; admin ve todos
CREATE POLICY "pedidos_select_own_or_admin"
    ON public.pedidos FOR SELECT
    TO authenticated
    USING (id_usuario = auth.uid() OR public.is_admin());

-- Cliente crea pedidos a su nombre
CREATE POLICY "pedidos_insert_own"
    ON public.pedidos FOR INSERT
    TO authenticated
    WITH CHECK (id_usuario = auth.uid());

-- Admin puede cambiar estado del pedido
CREATE POLICY "pedidos_update_admin"
    ON public.pedidos FOR UPDATE
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- ── ENVÍOS ──

-- Cliente ve envíos de sus pedidos; admin ve todos
CREATE POLICY "envios_select_own_or_admin"
    ON public.envios FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.pedidos p
            WHERE p.id = envios.id_pedido
              AND (p.id_usuario = auth.uid() OR public.is_admin())
        )
    );

-- Cliente crea envío ligado a su propio pedido
CREATE POLICY "envios_insert_own"
    ON public.envios FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.pedidos p
            WHERE p.id = envios.id_pedido
              AND p.id_usuario = auth.uid()
        )
    );

-- Admin actualiza estado de envío
CREATE POLICY "envios_update_admin"
    ON public.envios FOR UPDATE
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- ── 6. Datos iniciales (catálogo Punto Fit) ───────────────────

INSERT INTO public.productos (nombre, categoria, precio, inventario, imagen_url, descripcion, marca) VALUES
('Whey Protein Isolate',   'proteina',     45.99, 45, 'img/wheyprotein.webp', 'Proteína de suero aislada de alta pureza.', 'Optimum Nutrition'),
('Creatina Monohidratada', 'creatina',     29.99,  8, 'img/cratina.jpg',      'Creatina micronizada de alta calidad.',     'MuscleTech'),
('BCAA Amino Energy',      'aminoacidos',  24.50, 22, 'img/bcaa.png',         'BCAA con energía adicional.',               'ON'),
('C4 Pre-Workout',         'pre-workout',  35.00, 15, 'img/prework.webp',     'Pre-entreno con cafeína y beta-alanina.',   'Cellucor'),
('ISO 100 Protein',        'proteina',     55.00,  5, 'img/iso100.avif',      'Hidrolizado de proteína 100% ISO.',         'Dymatize'),
('Creatine HCL',           'creatina',     32.00, 30, 'img/hcl.avif',         'Creatina clorhidrato, alta solubilidad.',   'Kaged Muscle'),
('Mass Gainer Extreme',    'proteina',     48.00, 18, 'img/gainer.webp',      'Ganador de peso alto en calorías.',         'GAT Sport'),
('L-Glutamine 5000',       'aminoacidos',  19.99,  3, 'img/glutamine.jpg',    'L-Glutamina pura en polvo.',                'Now Sports');

-- ── 7. Crear tu primer admin (ejecutar DESPUÉS de registrarte) ─
--
-- 1) Regístrate en la app con admin@puntofit.com (o el correo que quieras).
-- 2) Ve a Supabase → Authentication → Users y copia el UUID del usuario.
-- 3) Ejecuta (reemplaza TU-UUID-AQUI):
--
-- UPDATE public.usuarios SET rol = 'admin' WHERE id = 'TU-UUID-AQUI';
--
-- ============================================================
